// TimeTrack NZ - Theme Definitions

export const lightTheme = {
  bg: '#f8fafc',
  card: '#ffffff',
  cardAlt: '#f1f5f9',
  cardBorder: '#e2e8f0',
  text: '#1e293b',
  textMuted: '#64748b',
  textLight: '#94a3b8',
  primary: '#2563eb',
  primaryHover: '#1d4ed8',
  success: '#16a34a',
  successBg: '#dcfce7',
  successText: '#15803d',
  warning: '#f59e0b',
  warningBg: '#fef3c7',
  warningText: '#b45309',
  danger: '#dc2626',
  dangerBg: '#fee2e2',
  input: '#ffffff',
  inputBorder: '#d1d5db',
  nav: '#ffffff',
  navBorder: '#e2e8f0',
};

export const darkTheme = {
  bg: '#0f172a',
  card: '#1e293b',
  cardAlt: '#334155',
  cardBorder: '#334155',
  text: '#f1f5f9',
  textMuted: '#94a3b8',
  textLight: '#64748b',
  primary: '#3b82f6',
  primaryHover: '#2563eb',
  success: '#22c55e',
  successBg: '#22c55e22',
  successText: '#4ade80',
  warning: '#f59e0b',
  warningBg: '#f59e0b22',
  warningText: '#fbbf24',
  danger: '#ef4444',
  dangerBg: '#ef444422',
  input: '#1e293b',
  inputBorder: '#334155',
  nav: '#1e293b',
  navBorder: '#334155',
};

export type Theme = typeof lightTheme;

// Shared styles generator
export const createStyles = (theme: Theme) => ({
  card: {
    background: theme.card,
    borderRadius: '16px',
    padding: '20px',
    marginBottom: '16px',
    border: `1px solid ${theme.cardBorder}`,
  } as React.CSSProperties,
  btn: {
    background: theme.primary,
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    padding: '14px 24px',
    fontWeight: '600' as const,
    fontSize: '15px',
    cursor: 'pointer',
  } as React.CSSProperties,
  btnDanger: {
    background: theme.danger,
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    padding: '14px 24px',
    fontWeight: '600' as const,
    fontSize: '15px',
    cursor: 'pointer',
  } as React.CSSProperties,
  btnSuccess: {
    background: theme.success,
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    padding: '14px 24px',
    fontWeight: '600' as const,
    fontSize: '15px',
    cursor: 'pointer',
  } as React.CSSProperties,
  btnSecondary: {
    background: theme.cardAlt,
    color: theme.text,
    border: `1px solid ${theme.cardBorder}`,
    borderRadius: '12px',
    padding: '14px 24px',
    fontWeight: '600' as const,
    fontSize: '15px',
    cursor: 'pointer',
  } as React.CSSProperties,
  input: {
    width: '100%',
    padding: '14px 16px',
    borderRadius: '12px',
    border: `1px solid ${theme.inputBorder}`,
    background: theme.input,
    color: theme.text,
    fontSize: '15px',
    boxSizing: 'border-box' as const,
  } as React.CSSProperties,
  select: {
    padding: '14px 16px',
    borderRadius: '12px',
    border: `1px solid ${theme.inputBorder}`,
    background: theme.input,
    color: theme.text,
    fontSize: '15px',
    boxSizing: 'border-box' as const,
    cursor: 'pointer',
  } as React.CSSProperties,
});
